export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';

export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
